/* eslint-disable */
import type * as auth from "../auth.js";
import type * as charges from "../charges.js";
import type * as dashboard from "../dashboard.js";
import type * as http from "../http.js";
import type * as invites from "../invites.js";
import type * as managers from "../managers.js";
import type * as me from "../me.js";
import type * as notices from "../notices.js";
import type * as payments from "../payments.js";
import type * as properties from "../properties.js";
import type * as scores from "../scores.js";
import type * as seed from "../seed.js";
import type * as session from "../session.js";
import type * as tenants from "../tenants.js";
import type * as units from "../units.js";
import type * as lib_audit from "../lib/audit.js";
import type * as lib_authz from "../lib/authz.js";
import type * as lib_charges from "../lib/charges.js";
import type * as lib_crypto from "../lib/crypto.js";
import type * as lib_dates from "../lib/dates.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_functions from "../lib/functions.js";
import type * as lib_limits from "../lib/limits.js";
import type * as lib_log from "../lib/log.js";
import type * as lib_principal from "../lib/principal.js";
import type * as lib_rateLimiter from "../lib/rateLimiter.js";
import type * as lib_rls from "../lib/rls.js";
import type * as lib_scoreEngine from "../lib/scoreEngine.js";
import type * as lib_scoring from "../lib/scoring.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * NOTE: Normally produced by `npx convex dev`. Committed so the project
 * type-checks without a live deployment; regenerated by re-running the CLI.
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  charges: typeof charges;
  dashboard: typeof dashboard;
  http: typeof http;
  invites: typeof invites;
  managers: typeof managers;
  me: typeof me;
  notices: typeof notices;
  payments: typeof payments;
  properties: typeof properties;
  scores: typeof scores;
  seed: typeof seed;
  session: typeof session;
  tenants: typeof tenants;
  units: typeof units;
  "lib/audit": typeof lib_audit;
  "lib/authz": typeof lib_authz;
  "lib/charges": typeof lib_charges;
  "lib/crypto": typeof lib_crypto;
  "lib/dates": typeof lib_dates;
  "lib/errors": typeof lib_errors;
  "lib/functions": typeof lib_functions;
  "lib/limits": typeof lib_limits;
  "lib/log": typeof lib_log;
  "lib/principal": typeof lib_principal;
  "lib/rateLimiter": typeof lib_rateLimiter;
  "lib/rls": typeof lib_rls;
  "lib/scoreEngine": typeof lib_scoreEngine;
  "lib/scoring": typeof lib_scoring;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

/**
 * Component references. Loosely typed here (hand-generated); `npx convex dev`
 * replaces this with the fully-typed component API.
 */
export declare const components: {
  rateLimiter: any;
};
